export default {
    unsavedRowsError: 'โปรดบันทึกแถวทั้งหมดก่อนดำเนินการต่อ',
    invalidRowsError: 'โปรดแก้ไขแถวที่ไม่ถูกต้องก่อนดำเนินการต่อ',
    invalidRowError: 'แถวไม่ถูกต้อง โปรดแก้ไขหรือลบ',
    alertMessageWithLabel: '{{label}}: {{message}}',
    alertMessage: '{{message}}',
    complete: 'ส่งข้อมูลสำเร็จ',
    error: 'โปรดแก้ไขข้อผิดพลาดต่อไปนี้ก่อนส่ง',
    errorListHotkey: 'กด Ctrl + Alt + X เพื่อกลับไปที่รายการข้อผิดพลาด',
    errorsListNavigationMessage: 'คลิกเพื่อนำทางไปยังฟิลด์ที่มีข้อผิดพลาดดังต่อไปนี้',
    submitError: 'โปรดตรวจสอบแบบฟอร์มและแก้ไขข้อผิดพลาดทั้งหมดก่อนส่ง',
    required: '{{field}} จำเป็นต้องระบุ',
    unique: '{{field}} ต้องไม่ซ้ำกัน',
    array: '{{field}} ต้องเป็นอาร์เรย์',
    array_nonempty: '{{field}} ต้องเป็นอาร์เรย์ที่ไม่ว่างเปล่า', // eslint-disable-line camelcase
    nonarray: '{{field}} ต้องไม่เป็นอาร์เรย์',
    select: '{{field}} มีการเลือกที่ไม่ถูกต้อง',
    pattern: '{{field}} ไม่ตรงตามรูปแบบ {{pattern}}',
    minLength: '{{field}} อย่างน้อยต้องมี {{length}} ตัว',
    maxLength: '{{field}} ต้องมีไม่เกิน {{length}} ตัว',
    minWords: '{{field}} อย่างน้อยต้องมี {{length}} คำ',
    maxWords: '{{field}} ต้องมีไม่เกิน {{length}} คำ',
    min: '{{field}} ไม่น้อยกว่า {{min}}.',
    max: '{{field}} ไม่สามารถมากกว่า {{max}}.',
    maxDate: '{{field}} ไม่ควรมีวันที่หลัง {{- maxDate}}',
    minDate: '{{field}} ไม่ควรมีวันที่ก่อนหน้า {{- minDate}}',
    maxYear: '{{field}} ไม่ควรมีปีที่มากว่า {{maxYear}}',
    minYear: '{{field}} ไม่ควรมีปีที่น้อยกว่า {{minYear}}',
    invalid_email: '{{field}} ต้องเป็นอีเมลที่ถูกต้อง', // eslint-disable-line camelcase
    invalid_url: '{{field}} ต้องเป็น URL ที่ถูกต้อง', // eslint-disable-line camelcase
    invalid_regex: '{{field}} ไม่ตรงตามรูปแบบ {{regex}}.', // eslint-disable-line camelcase
    invalid_date: '{{field}} ไม่ใช่วันที่ถูกต้อง', // eslint-disable-line camelcase
    invalid_day: '{{field}} ไม่ใช่วันที่ถูกต้อง', // eslint-disable-line camelcase
    mask: '{{field}} ไม่ตรงกับรูปแบบที่กำหนด',
    valueIsNotAvailable: '{{ field }} เป็นค่าที่ไม่ถูกต้อง',
    stripe: '{{stripe}}',
    month: 'เดือน',
    day: 'วัน',
    year: 'ปี',
    january: 'มกราคม',
    february: 'กุมภาพันธ์',
    march: 'มีนาคม',
    april: 'เมษายน',
    may: 'พฤษภาคม',
    june: 'มิถุนายน',
    july: 'กรกฎาคม',
    august: 'สิงหาคม',
    september: 'กันยายน',
    october: 'ตุลาคม',
    november: 'พฤศจิกายน',
    december: 'ธันวาคม',
    next: 'ถัดไป',
    previous: 'ย้อนกลับ',
    cancel: 'ยกเลิก',
    submit: 'ส่งข้อมูล',
    confirmCancel: 'คุณแน่ใจหรือว่าต้องการยกเลิก',
    saveDraftInstanceError: 'ไม่สามารถบันทึกฉบับร่างได้เนื่องจากไม่มีอินสแตนซ์ของ formio',
    saveDraftAuthError: 'ไม่สามารถบันทึกฉบับร่างได้ เว้นแต่ผู้ใช้จะได้รับการตรวจสอบสิทธิ์',
    restoreDraftInstanceError: 'ไม่สามารถกู้คืนร่างจดหมายได้เนื่องจากไม่มีอินสแตนซ์ของ formio',
    time: 'เวลาไม่ถูกต้อง',
    'File Name': 'ชื่อเอกสาร',
    Size:'ขนาด',
    Type: 'ชนิด',
    'Drop files to attach,': 'ลาก,',
    or: 'หรือ ',
    browse: 'เลือกไฟล์เพื่อแนบ',
    'Processing file. Please wait...': 'กำลังประมวลผลไฟล์. โปรดรอ...',
    'File with the same name is already uploaded': 'ไฟล์ที่มีชื่อเดียวกันถูกอัปโหลดแล้ว',
    'File is the wrong type; it must be {{ pattern }}': 'ไฟล์เป็นประเภทที่ไม่ถูกต้อง ต้องเป็น {{ pattern }}',
    'File is too small; it must be at least {{ size }}': 'ไฟล์มีขนาดเล็กเกินไป ต้องมีอย่างน้อย {{ size }}',
    'File is too big; it must be at most {{ size }}': 'ไฟล์ใหญ่เกินไป ต้องมีขนาดไม่เกิน {{ size }}',
    'File Service not provided.': 'ไม่ได้ให้บริการไฟล์',
    'File processing has been failed.': 'การประมวลผลไฟล์ล้มเหลว',
    'Starting upload.': 'กำลังเริ่มอัปโหลด',
    'No choices to choose from':'ไม่มีตัวเลือกให้เลือก',
    'No results found':'ไม่พบผลลัพธ์',
};
